<?php

use Illuminate\Database\Seeder;

class CountryCodesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('country_codes')->insert(         [
            ["full_name" => "Afghanistan", "short_name" => "af"],
            ["full_name" => "Åland Islands", "short_name" => "ax"],
            ["full_name" => "Albania", "short_name" => "al"],
            ["full_name" => "Algeria", "short_name" => "dz"],
            ["full_name" => "American Samoa", "short_name" => "as"],
            ["full_name" => "Andorra", "short_name" => "ad"],
            ["full_name" => "Angola", "short_name" => "ao"],
            ["full_name" => "Anguilla", "short_name" => "ai"],
            ["full_name" => "Antarctica", "short_name" => "aq"],
            ["full_name" => "Antigua and Barbuda", "short_name" => "ag"],
            ["full_name" => "Argentina", "short_name" => "ar"],
            ["full_name" => "Armenia", "short_name" => "am"],
            ["full_name" => "Aruba", "short_name" => "aw"],
            ["full_name" => "Australia", "short_name" => "au"],
            ["full_name" => "Austria", "short_name" => "at"],
            ["full_name" => "Azerbaijan", "short_name" => "az"],
            ["full_name" => "Bahamas", "short_name" => "bs"],
            ["full_name" => "Bahrain", "short_name" => "bh"],
            ["full_name" => "Bangladesh", "short_name" => "bd"],
            ["full_name" => "Barbados", "short_name" => "bb"],
            ["full_name" => "Belarus", "short_name" => "by"],
            ["full_name" => "Belgium", "short_name" => "be"],
            ["full_name" => "Belize", "short_name" => "bz"],
            ["full_name" => "Benin", "short_name" => "bj"],
            ["full_name" => "Bermuda", "short_name" => "bm"],
            ["full_name" => "Bhutan", "short_name" => "bt"],
            ["full_name" => "Bolivia (Plurinational State of)", "short_name" => "bo"],
            ["full_name" => "Bonaire, Sint Eustatius and Saba", "short_name" => "bq"],
            ["full_name" => "Bosnia and Herzegovina", "short_name" => "ba"],
            ["full_name" => "Botswana", "short_name" => "bw"],
            ["full_name" => "Bouvet Island", "short_name" => "bv"],
            ["full_name" => "Brazil", "short_name" => "br"],
            ["full_name" => "British Indian Ocean Territory", "short_name" => "io"],
            ["full_name" => "Brunei Darussalam", "short_name" => "bn"],
            ["full_name" => "Bulgaria", "short_name" => "bg"],
            ["full_name" => "Burkina Faso", "short_name" => "bf"],
            ["full_name" => "Burundi", "short_name" => "bi"],
            ["full_name" => "Cabo Verde", "short_name" => "cv"],
            ["full_name" => "Cambodia", "short_name" => "kh"],
            ["full_name" => "Cameroon", "short_name" => "cm"],
            ["full_name" => "Canada", "short_name" => "ca"],
            ["full_name" => "Cayman Islands", "short_name" => "ky"],
            ["full_name" => "Central African Republic", "short_name" => "cf"],
            ["full_name" => "Chad", "short_name" => "td"],
            ["full_name" => "Chile", "short_name" => "cl"],
            ["full_name" => "China", "short_name" => "cn"],
            ["full_name" => "Christmas Island", "short_name" => "cx"],
            ["full_name" => "Cocos (Keeling) Islands", "short_name" => "cc"],
            ["full_name" => "Colombia", "short_name" => "co"],
            ["full_name" => "Comoros", "short_name" => "km"],
            ["full_name" => "Congo", "short_name" => "cg"],
            ["full_name" => "Congo (Democratic Republic of the)", "short_name" => "cd"],
            ["full_name" => "Cook Islands", "short_name" => "ck"],
            ["full_name" => "Costa Rica", "short_name" => "cr"],
            ["full_name" => "Côte d'Ivoire", "short_name" => "ci"],
            ["full_name" => "Croatia", "short_name" => "hr"],
            ["full_name" => "Cuba", "short_name" => "cu"],
            ["full_name" => "Curaçao", "short_name" => "cw"],
            ["full_name" => "Cyprus", "short_name" => "cy"],
            ["full_name" => "Czechia", "short_name" => "cz"],
            ["full_name" => "Denmark", "short_name" => "dk"],
            ["full_name" => "Djibouti", "short_name" => "dj"],
            ["full_name" => "Dominica", "short_name" => "dm"],
            ["full_name" => "Dominican Republic", "short_name" => "do"],
            ["full_name" => "Ecuador", "short_name" => "ec"],
            ["full_name" => "Egypt", "short_name" => "eg"],
            ["full_name" => "El Salvador", "short_name" => "sv"],
            ["full_name" => "Equatorial Guinea", "short_name" => "gq"],
            ["full_name" => "Eritrea", "short_name" => "er"],
            ["full_name" => "Estonia", "short_name" => "ee"],
            ["full_name" => "Eswatini", "short_name" => "sz"],
            ["full_name" => "Ethiopia", "short_name" => "et"],
            ["full_name" => "Falkland Islands (Malvinas)", "short_name" => "fk"],
            ["full_name" => "Faroe Islands", "short_name" => "fo"],
            ["full_name" => "Fiji", "short_name" => "fj"],
            ["full_name" => "Finland", "short_name" => "fi"],
            ["full_name" => "France", "short_name" => "fr"],
            ["full_name" => "French Guiana", "short_name" => "gf"],
            ["full_name" => "French Polynesia", "short_name" => "pf"],
            ["full_name" => "French Southern Territories", "short_name" => "tf"],
            ["full_name" => "Gabon", "short_name" => "ga"],
            ["full_name" => "Gambia", "short_name" => "gm"],
            ["full_name" => "Georgia", "short_name" => "ge"],
            ["full_name" => "Germany", "short_name" => "de"],
            ["full_name" => "Ghana", "short_name" => "gh"],
            ["full_name" => "Gibraltar", "short_name" => "gi"],
            ["full_name" => "Greece", "short_name" => "gr"],
            ["full_name" => "Greenland", "short_name" => "gl"],
            ["full_name" => "Grenada", "short_name" => "gd"],
            ["full_name" => "Guadeloupe", "short_name" => "gp"],
            ["full_name" => "Guam", "short_name" => "gu"],
            ["full_name" => "Guatemala", "short_name" => "gt"],
            ["full_name" => "Guernsey", "short_name" => "gg"],
            ["full_name" => "Guinea", "short_name" => "gn"],
            ["full_name" => "Guinea-Bissau", "short_name" => "gw"],
            ["full_name" => "Guyana", "short_name" => "gy"],
            ["full_name" => "Haiti", "short_name" => "ht"],
            ["full_name" => "Heard Island and McDonald Islands", "short_name" => "hm"],
            ["full_name" => "Holy See", "short_name" => "va"],
            ["full_name" => "Honduras", "short_name" => "hn"],
            ["full_name" => "Hong Kong", "short_name" => "hk"],
            ["full_name" => "Hungary", "short_name" => "hu"],
            ["full_name" => "Iceland", "short_name" => "is"],
            ["full_name" => "India", "short_name" => "in"],
            ["full_name" => "Indonesia", "short_name" => "id"],
            ["full_name" => "Iran (Islamic Republic of)", "short_name" => "ir"],
            ["full_name" => "Iraq", "short_name" => "iq"],
            ["full_name" => "Ireland", "short_name" => "ie"],
            ["full_name" => "Isle of Man", "short_name" => "im"],
            ["full_name" => "Israel", "short_name" => "il"],
            ["full_name" => "Italy", "short_name" => "it"],
            ["full_name" => "Jamaica", "short_name" => "jm"],
            ["full_name" => "Japan", "short_name" => "jp"],
            ["full_name" => "Jersey", "short_name" => "je"],
            ["full_name" => "Jordan", "short_name" => "jo"],
            ["full_name" => "Kazakhstan", "short_name" => "kz"],
            ["full_name" => "Kenya", "short_name" => "ke"],
            ["full_name" => "Kiribati", "short_name" => "ki"],
            ["full_name" => "Korea (Democratic People's Republic of)", "short_name" => "kp"],
            ["full_name" => "Korea (Republic of)", "short_name" => "kr"],
            ["full_name" => "Kuwait", "short_name" => "kw"],
            ["full_name" => "Kyrgyzstan", "short_name" => "kg"],
            ["full_name" => "Lao People's Democratic Republic", "short_name" => "la"],
            ["full_name" => "Latvia", "short_name" => "lv"],
            ["full_name" => "Lebanon", "short_name" => "lb"],
            ["full_name" => "Lesotho", "short_name" => "ls"],
            ["full_name" => "Liberia", "short_name" => "lr"],
            ["full_name" => "Libya", "short_name" => "ly"],
            ["full_name" => "Liechtenstein", "short_name" => "li"],
            ["full_name" => "Lithuania", "short_name" => "lt"],
            ["full_name" => "Luxembourg", "short_name" => "lu"],
            ["full_name" => "Macao", "short_name" => "mo"],
            ["full_name" => "Macedonia (the former Yugoslav Republic of)", "short_name" => "mk"],
            ["full_name" => "Madagascar", "short_name" => "mg"],
            ["full_name" => "Malawi", "short_name" => "mw"],
            ["full_name" => "Malaysia", "short_name" => "my"],
            ["full_name" => "Maldives", "short_name" => "mv"],
            ["full_name" => "Mali", "short_name" => "ml"],
            ["full_name" => "Malta", "short_name" => "mt"],
            ["full_name" => "Marshall Islands", "short_name" => "mh"],
            ["full_name" => "Martinique", "short_name" => "mq"],
            ["full_name" => "Mauritania", "short_name" => "mr"],
            ["full_name" => "Mauritius", "short_name" => "mu"],
            ["full_name" => "Mayotte", "short_name" => "yt"],
            ["full_name" => "Mexico", "short_name" => "mx"],
            ["full_name" => "Micronesia (Federated States of)", "short_name" => "fm"],
            ["full_name" => "Moldova (Republic of)", "short_name" => "md"],
            ["full_name" => "Monaco", "short_name" => "mc"],
            ["full_name" => "Mongolia", "short_name" => "mn"],
            ["full_name" => "Montenegro", "short_name" => "me"],
            ["full_name" => "Montserrat", "short_name" => "ms"],
            ["full_name" => "Morocco", "short_name" => "ma"],
            ["full_name" => "Mozambique", "short_name" => "mz"],
            ["full_name" => "Myanmar", "short_name" => "mm"],
            ["full_name" => "Namibia", "short_name" => "na"],
            ["full_name" => "Nauru", "short_name" => "nr"],
            ["full_name" => "Nepal", "short_name" => "np"],
            ["full_name" => "Netherlands", "short_name" => "nl"],
            ["full_name" => "New Caledonia", "short_name" => "nc"],
            ["full_name" => "New Zealand", "short_name" => "nz"],
            ["full_name" => "Nicaragua", "short_name" => "ni"],
            ["full_name" => "Niger", "short_name" => "ne"],
            ["full_name" => "Nigeria", "short_name" => "ng"],
            ["full_name" => "Niue", "short_name" => "nu"],
            ["full_name" => "Norfolk Island", "short_name" => "nf"],
            ["full_name" => "Northern Mariana Islands", "short_name" => "mp"],
            ["full_name" => "Norway", "short_name" => "no"],
            ["full_name" => "Oman", "short_name" => "om"],
            ["full_name" => "Pakistan", "short_name" => "pk"],
            ["full_name" => "Palau", "short_name" => "pw"],
            ["full_name" => "Palestine, State of", "short_name" => "ps"],
            ["full_name" => "Panama", "short_name" => "pa"],
            ["full_name" => "Papua New Guinea", "short_name" => "pg"],
            ["full_name" => "Paraguay", "short_name" => "py"],
            ["full_name" => "Peru", "short_name" => "pe"],
            ["full_name" => "Philippines", "short_name" => "ph"],
            ["full_name" => "Pitcairn", "short_name" => "pn"],
            ["full_name" => "Poland", "short_name" => "pl"],
            ["full_name" => "Portugal", "short_name" => "pt"],
            ["full_name" => "Puerto Rico", "short_name" => "pr"],
            ["full_name" => "Qatar", "short_name" => "qa"],
            ["full_name" => "Réunion", "short_name" => "re"],
            ["full_name" => "Romania", "short_name" => "ro"],
            ["full_name" => "Russian Federation", "short_name" => "ru"],
            ["full_name" => "Rwanda", "short_name" => "rw"],
            ["full_name" => "Saint Barthélemy", "short_name" => "bl"],
            ["full_name" => "Saint Helena, Ascension and Tristan da Cunha", "short_name" => "sh"],
            ["full_name" => "Saint Kitts and Nevis", "short_name" => "kn"],
            ["full_name" => "Saint Lucia", "short_name" => "lc"],
            ["full_name" => "Saint Martin (French part)", "short_name" => "mf"],
            ["full_name" => "Saint Pierre and Miquelon", "short_name" => "pm"],
            ["full_name" => "Saint Vincent and the Grenadines", "short_name" => "vc"],
            ["full_name" => "Samoa", "short_name" => "ws"],
            ["full_name" => "San Marino", "short_name" => "sm"],
            ["full_name" => "Sao Tome and Principe", "short_name" => "st"],
            ["full_name" => "Saudi Arabia", "short_name" => "sa"],
            ["full_name" => "Senegal", "short_name" => "sn"],
            ["full_name" => "Serbia", "short_name" => "rs"],
            ["full_name" => "Seychelles", "short_name" => "sc"],
            ["full_name" => "Sierra Leone", "short_name" => "sl"],
            ["full_name" => "Singapore", "short_name" => "sg"],
            ["full_name" => "Sint Maarten (Dutch part)", "short_name" => "sx"],
            ["full_name" => "Slovakia", "short_name" => "sk"],
            ["full_name" => "Slovenia", "short_name" => "si"],
            ["full_name" => "Solomon Islands", "short_name" => "sb"],
            ["full_name" => "Somalia", "short_name" => "so"],
            ["full_name" => "South Africa", "short_name" => "za"],
            ["full_name" => "South Georgia and the South Sandwich Islands", "short_name" => "gs"],
            ["full_name" => "South Sudan", "short_name" => "ss"],
            ["full_name" => "Spain", "short_name" => "es"],
            ["full_name" => "Sri Lanka", "short_name" => "lk"],
            ["full_name" => "Sudan", "short_name" => "sd"],
            ["full_name" => "Suriname", "short_name" => "sr"],
            ["full_name" => "Svalbard and Jan Mayen", "short_name" => "sj"],
            ["full_name" => "Sweden", "short_name" => "se"],
            ["full_name" => "Switzerland", "short_name" => "ch"],
            ["full_name" => "Syrian Arab Republic", "short_name" => "sy"],
            ["full_name" => "Taiwan, Province of China", "short_name" => "tw"],
            ["full_name" => "Tajikistan", "short_name" => "tj"],
            ["full_name" => "Tanzania, United Republic of", "short_name" => "tz"],
            ["full_name" => "Thailand", "short_name" => "th"],
            ["full_name" => "Timor-Leste", "short_name" => "tl"],
            ["full_name" => "Togo", "short_name" => "tg"],
            ["full_name" => "Tokelau", "short_name" => "tk"],
            ["full_name" => "Tonga", "short_name" => "to"],
            ["full_name" => "Trinidad and Tobago", "short_name" => "tt"],
            ["full_name" => "Tunisia", "short_name" => "tn"],
            ["full_name" => "Turkey", "short_name" => "tr"],
            ["full_name" => "Turkmenistan", "short_name" => "tm"],
            ["full_name" => "Turks and Caicos Islands", "short_name" => "tc"],
            ["full_name" => "Tuvalu", "short_name" => "tv"],
            ["full_name" => "Uganda", "short_name" => "ug"],
            ["full_name" => "Ukraine", "short_name" => "ua"],
            ["full_name" => "United Arab Emirates", "short_name" => "ae"],
            ["full_name" => "United Kingdom", "short_name" => "gb"],
            ["full_name" => "United States of America", "short_name" => "us"],
            ["full_name" => "United States Minor Outlying Islands", "short_name" => "um"],
            ["full_name" => "Uruguay", "short_name" => "uy"],
            ["full_name" => "Uzbekistan", "short_name" => "uz"],
            ["full_name" => "Vanuatu", "short_name" => "vu"],
            ["full_name" => "Venezuela (Bolivarian Republic of)", "short_name" => "ve"],
            ["full_name" => "Viet Nam", "short_name" => "vn"],
            ["full_name" => "Virgin Islands (British)", "short_name" => "vg"],
            ["full_name" => "Virgin Islands (U.S.)", "short_name" => "vi"],
            ["full_name" => "Wallis and Futuna", "short_name" => "wf"],
            ["full_name" => "Western Sahara", "short_name" => "eh"],
            ["full_name" => "Yemen", "short_name" => "ye"],
            ["full_name" => "Zambia", "short_name" => "zm"],
            ["full_name" => "Zimbabwe", "short_name" => "zw"]
        ]);
    }
}
