-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Aug 30, 2018 at 05:01 PM
-- Server version: 8.0.11
-- PHP Version: 7.2.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `glance.tk`
--

--
-- Dumping data for table `sources`
--

INSERT INTO `sources` (`id`, `name`, `description`, `url`, `category`, `language`, `country_short_name`, `country_full_name`, `updated_at`) VALUES
(1, 'ABC News', 'Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.', 'http://abcnews.go.com', 'general', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(2, 'ABC News (AU)', 'Australia\'s most trusted source of local, national and world news. Comprehensive, independent, in-depth analysis, the latest business, sport, weather and more.', 'http://www.abc.net.au/news', 'general', 'English', 'au', 'Australia', '2018-08-30 16:55:09'),
(3, 'Aftenposten', 'Norges ledende nettavis med alltid oppdaterte nyheter innenfor innenriks, utenriks, sport og kultur.', 'https://www.aftenposten.no', 'general', 'Norwegian', 'no', 'Norway', '2018-08-30 16:55:09'),
(4, 'Al Jazeera English', 'News, analysis from the Middle East and worldwide, multimedia and interactives, opinions, documentaries, podcasts, long reads and broadcast schedule.', 'http://www.aljazeera.com', 'general', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(5, 'ANSA.it', 'Agenzia ANSA: ultime notizie, foto, video e approfondimenti su: cronaca, politica, economia, regioni, mondo, sport, calcio, cultura e tecnologia.', 'http://www.ansa.it', 'general', 'Italian', 'it', 'Italy', '2018-08-30 16:55:09'),
(6, 'Argaam', 'ارقام موقع متخصص في متابعة سوق الأسهم السعودي تداول - تاسي - مع تغطيه معمقة لشركات واسعار ومنتجات البتروكيماويات , تقارير مالية الاكتتابات الجديده ', 'http://www.argaam.com', 'business', 'Arabic', 'sa', 'Saudi Arabia', '2018-08-30 16:55:09'),
(7, 'Ars Technica', 'The PC enthusiast\'s resource. Power users and the tools they love, without computing religion.', 'http://arstechnica.com', 'technology', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(8, 'Ary News', 'ARY News is a Pakistani news channel committed to bring you up-to-the minute Pakistan news and featured stories from around Pakistan and all over the world.', 'https://arynews.tv/ud/', 'general', 'Urdu', 'pk', 'Pakistan', '2018-08-30 16:55:09'),
(9, 'Associated Press', 'The AP delivers in-depth coverage on the international, politics, lifestyle, business, and entertainment news.', 'https://apnews.com/', 'general', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(10, 'Australian Financial Review', 'The Australian Financial Review reports the latest news from business, finance, investment and politics, updated in real time. It has a reputation for independent, award-winning journalism and is essential reading for the business and investor community.', 'http://www.afr.com', 'business', 'English', 'au', 'Australia', '2018-08-30 16:55:09'),
(11, 'Axios', 'Axios are a new media company delivering vital, trustworthy news and analysis in the most efficient, illuminating and shareable ways possible.', 'https://www.axios.com', 'general', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(12, 'BBC News', 'Use BBC News for up-to-the-minute news, breaking news, video, audio and feature stories. BBC News provides trusted World and UK news as well as local and regional perspectives. Also entertainment, business, science, technology and health news.', 'http://www.bbc.co.uk/news', 'general', 'English', 'gb', 'United Kingdom', '2018-08-30 17:00:30'),
(13, 'BBC Sport', 'The home of BBC Sport online. Includes live sports coverage, breaking news, results, video, audio and analysis on Football, F1, Cricket, Rugby Union, Rugby League, Golf, Tennis and all the main world sports, plus major events such as the Olympic Games.', 'http://www.bbc.co.uk/sport', 'sports', 'English', 'gb', 'United Kingdom', '2018-08-30 17:00:30'),
(14, 'Bild', 'Die Seite 1 für aktuelle Nachrichten und Themen, Bilder und Videos aus den Bereichen News, Wirtschaft, Politik, Show, Sport, und Promis.', 'http://www.bild.de', 'general', 'German', 'de', 'Germany', '2018-08-30 16:55:09'),
(15, 'Blasting News (BR)', 'Descubra a seção brasileira da Blasting News, a primeira revista feita pelo  público, com notícias globais e vídeos independentes. Junte-se a nós e torne- se um repórter.', 'http://br.blastingnews.com', 'general', 'Portuguese', 'br', 'Brazil', '2018-08-30 16:55:09'),
(16, 'Bleacher Report', 'Sports journalists and bloggers covering NFL, MLB, NBA, NHL, MMA, college football and basketball, NASCAR, fantasy sports and more. News, photos, mock drafts, game scores, player profiles and more!', 'http://www.bleacherreport.com', 'sports', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(17, 'Bloomberg', 'Bloomberg delivers business and markets news, data, analysis, and video to the world, featuring stories from Businessweek and Bloomberg News.', 'http://www.bloomberg.com', 'business', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(18, 'Breitbart News', 'Syndicated news and opinion website providing continuously updated headlines to top news and analysis sources.', 'http://www.breitbart.com', 'general', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(19, 'Business Insider', 'Business Insider is a fast-growing business site with deep financial, media, tech, and other industry verticals. Launched in 2007, the site is now the largest business news site on the web.', 'http://www.businessinsider.com', 'business', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(20, 'Business Insider (UK)', 'Business Insider is a fast-growing business site with deep financial, media, tech, and other industry verticals. Launched in 2007, the site is now the largest business news site on the web.', 'http://uk.businessinsider.com', 'business', 'English', 'gb', 'United Kingdom', '2018-08-30 17:00:30'),
(21, 'Buzzfeed', 'BuzzFeed is a cross-platform, global network for news and entertainment that generates seven billion views each month.', 'https://www.buzzfeed.com', 'entertainment', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(22, 'CBC News', 'CBC News is the division of the Canadian Broadcasting Corporation responsible for the news gathering and production of news programs on the corporation\'s English-language operations, namely CBC Television, CBC Radio, CBC News Network, and CBC.ca.', 'http://www.cbc.ca/news', 'general', 'English', 'ca', 'Canada', '2018-08-30 16:55:09'),
(23, 'CBS News', 'CBS News: dedicated to providing the best in journalism under standards it pioneered at the dawn of radio and television and continue in the digital age.', 'http://www.cbsnews.com', 'general', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(24, 'CNBC', 'Get latest business news on stock markets, financial & earnings on CNBC. View world markets streaming charts & video; check stock tickers and quotes.', 'http://www.cnbc.com', 'business', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(25, 'CNN', 'View the latest news and breaking news today for U.S., world, weather, entertainment, politics and health at CNN', 'http://us.cnn.com', 'general', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(26, 'CNN Spanish', 'Lee las últimas noticias e información sobre Latinoamérica, Estados Unidos, mundo, entretenimiento, política, salud, tecnología y deportes en CNNEspañol.com.', 'http://cnnespanol.cnn.com/', 'general', 'Spanish', 'us', 'United States of America', '2018-08-30 16:55:09'),
(27, 'Crypto Coins News', 'Providing breaking cryptocurrency news - focusing on Bitcoin, Ethereum, ICOs, blockchain technology, and smart contracts.', 'https://www.ccn.com', 'technology', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(28, 'Daily Mail', 'All the latest news, sport, showbiz, science and health stories from around the world from the Daily Mail and Mail on Sunday newspapers.', 'http://www.dailymail.co.uk/home/index.html', 'entertainment', 'English', 'gb', 'United Kingdom', '2018-08-30 17:00:30'),
(29, 'Der Tagesspiegel', 'Nachrichten, News und neueste Meldungen aus dem Inland und dem Ausland - aktuell präsentiert von tagesspiegel.de.', 'http://www.tagesspiegel.de', 'general', 'German', 'de', 'Germany', '2018-08-30 16:55:09'),
(30, 'Die Zeit', 'Aktuelle Nachrichten, Kommentare, Analysen und Hintergrundberichte aus Politik, Wirtschaft, Gesellschaft, Wissen, Kultur und Sport lesen Sie auf ZEIT ONLINE.', 'http://www.zeit.de/index', 'business', 'German', 'de', 'Germany', '2018-08-30 16:55:09'),
(31, 'El Mundo', 'Noticias, actualidad, álbumes, debates, sociedad, servicios, entretenimiento y última hora en España y el mundo.', 'http://www.elmundo.es', 'general', 'Spanish', 'es', 'Spain', '2018-08-30 16:55:09'),
(32, 'Engadget', 'Engadget is a web magazine with obsessive daily coverage of everything new in gadgets and consumer electronics.', 'https://www.engadget.com', 'technology', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(33, 'Entertainment Weekly', 'Online version of the print magazine includes entertainment news, interviews, reviews of music, film, TV and books, and a special area for magazine subscribers.', 'http://www.ew.com', 'entertainment', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(34, 'ESPN', 'ESPN has up-to-the-minute sports news coverage, scores, highlights and commentary for NFL, MLB, NBA, College Football, NCAA Basketball and more.', 'http://espn.go.com', 'sports', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(35, 'ESPN Cric Info', 'ESPN Cricinfo provides the most comprehensive cricket coverage available including live ball-by-ball commentary, news, unparalleled statistics, quality editorial comment and analysis.', 'http://www.espncricinfo.com/', 'sports', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(36, 'Financial Post', 'Find the latest happenings in the Canadian Financial Sector and stay up to date with changing trends in Business Markets. Read trading and investing advice from professionals.', 'http://business.financialpost.com', 'business', 'English', 'ca', 'Canada', '2018-08-30 16:55:09'),
(37, 'Financial Times', 'The latest UK and international business, finance, economic and political news, comment and analysis from the Financial Times on FT.com.', 'http://www.ft.com/home/uk', 'business', 'English', 'gb', 'United Kingdom', '2018-08-30 17:00:30'),
(38, 'Focus', 'Minutenaktuelle Nachrichten und Service-Informationen von Deutschlands modernem Nachrichtenmagazin.', 'http://www.focus.de', 'general', 'German', 'de', 'Germany', '2018-08-30 16:55:09'),
(39, 'Football Italia', 'Italian football news, analysis, fixtures and results for the latest from Serie A, Serie B and the Azzurri.', 'http://www.football-italia.net', 'sports', 'English', 'it', 'Italy', '2018-08-30 16:55:09'),
(40, 'Fortune', 'Fortune 500 Daily and Breaking Business News', 'http://fortune.com', 'business', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(41, 'FourFourTwo', 'The latest football news, in-depth features, tactical and statistical analysis from FourFourTwo, the UK&#039;s favourite football monthly.', 'http://www.fourfourtwo.com/news', 'sports', 'English', 'gb', 'United Kingdom', '2018-08-30 17:00:30'),
(42, 'Fox News', 'Breaking News, Latest News and Current News from FOXNews.com. Breaking news and video. Latest Current News: U.S., World, Entertainment, Health, Business, Technology, Politics, Sports.', 'http://www.foxnews.com', 'general', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(43, 'Fox Sports', 'Find live scores, player and team news, videos, rumors, stats, standings, schedules and fantasy games on FOX Sports.', 'http://www.foxsports.com', 'sports', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(44, 'Globo', 'Só na globo.com você encontra tudo sobre o conteúdo e marcas do Grupo Globo. O melhor acervo de vídeos online sobre entretenimento, esportes e jornalismo do Brasil.', 'http://www.globo.com/', 'general', 'Portuguese', 'br', 'Brazil', '2018-08-30 16:55:09'),
(45, 'Google News', 'Comprehensive, up-to-date news coverage, aggregated from sources all over the world by Google News.', 'https://news.google.com', 'general', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(46, 'Google News (Argentina)', 'Completa cobertura actualizada de noticias agregadas a partir de fuentes de todo el mundo por Google Noticias.', 'https://news.google.com', 'general', 'Spanish', 'ar', 'Argentina', '2018-08-30 16:55:09'),
(47, 'Google News (Australia)', 'Comprehensive, up-to-date Australia news coverage, aggregated from sources all over the world by Google News.', 'https://news.google.com', 'general', 'English', 'au', 'Australia', '2018-08-30 16:55:09'),
(48, 'Google News (Brasil)', 'Cobertura jornalística abrangente e atualizada, agregada de fontes do mundo inteiro pelo Google Notícias.', 'https://news.google.com', 'general', 'Portuguese', 'br', 'Brazil', '2018-08-30 16:55:09'),
(49, 'Google News (Canada)', 'Comprehensive, up-to-date Canada news coverage, aggregated from sources all over the world by Google News.', 'https://news.google.com', 'general', 'English', 'ca', 'Canada', '2018-08-30 16:55:09'),
(50, 'Google News (France)', 'Informations complètes et à jour, compilées par Google Actualités à partir de sources d&#39;actualités du monde entier.', 'https://news.google.com', 'general', 'French', 'fr', 'France', '2018-08-30 16:55:09'),
(51, 'Google News (India)', 'Comprehensive, up-to-date India news coverage, aggregated from sources all over the world by Google News.', 'https://news.google.com', 'general', 'English', 'in', 'India', '2018-08-30 16:55:09'),
(52, 'Google News (Israel)', 'כיסוי מקיף ועדכני של חדשות שהצטברו ממקורות בכל העולם על ידי &#39;חדשות Google&#39;.', 'https://news.google.com', 'general', 'Hebrew', 'il', 'Israel', '2018-08-30 16:55:09'),
(53, 'Google News (Italy)', 'Copertura giornalistica completa e aggiornata ottenuta combinando fonti di notizie in tutto il mondo attraverso Google News.', 'https://news.google.com', 'general', 'Italian', 'it', 'Italy', '2018-08-30 16:55:09'),
(54, 'Google News (Russia)', 'Исчерпывающая и актуальная информация, собранная службой &quot;Новости Google&quot; со всего света.', 'https://news.google.com', 'general', 'Russian', 'ru', 'Russian Federation', '2018-08-30 16:55:09'),
(55, 'Google News (Saudi Arabia)', 'تغطية شاملة ومتجددة للأخبار، تم جمعها من مصادر أخبار من جميع أنحاء العالم بواسطة أخبار Google.', 'https://news.google.com', 'general', 'Arabic', 'sa', 'Saudi Arabia', '2018-08-30 16:55:09'),
(56, 'Google News (UK)', 'Comprehensive, up-to-date UK news coverage, aggregated from sources all over the world by Google News.', 'https://news.google.com', 'general', 'English', 'gb', 'United Kingdom', '2018-08-30 17:00:30'),
(57, 'Göteborgs-Posten', 'Göteborgs-Posten, abbreviated GP, is a major Swedish language daily newspaper published in Gothenburg, Sweden.', 'http://www.gp.se', 'general', 'Swedish', 'se', 'Sweden', '2018-08-30 16:55:09'),
(58, 'Gruenderszene', 'Online-Magazin für Startups und die digitale Wirtschaft. News und Hintergründe zu Investment, VC und Gründungen.', 'http://www.gruenderszene.de', 'technology', 'German', 'de', 'Germany', '2018-08-30 16:55:09'),
(59, 'Hacker News', 'Hacker News is a social news website focusing on computer science and entrepreneurship. It is run by Paul Graham\'s investment fund and startup incubator, Y Combinator. In general, content that can be submitted is defined as \"anything that gratifies one\'s intellectual curiosity\".', 'https://news.ycombinator.com', 'technology', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(60, 'Handelsblatt', 'Auf Handelsblatt lesen sie Nachrichten über Unternehmen, Finanzen, Politik und Technik. Verwalten Sie Ihre Finanzanlagen mit Hilfe unserer Börsenkurse.', 'http://www.handelsblatt.com', 'business', 'German', 'de', 'Germany', '2018-08-30 16:55:09'),
(61, 'IGN', 'IGN is your site for Xbox One, PS4, PC, Wii-U, Xbox 360, PS3, Wii, 3DS, PS Vita and iPhone games with expert reviews, news, previews, trailers, cheat codes, wiki guides and walkthroughs.', 'http://www.ign.com', 'entertainment', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(62, 'Il Sole 24 Ore', 'Notizie di economia, cronaca italiana ed estera, quotazioni borsa in tempo reale e di finanza, norme e tributi, fondi e obbligazioni, mutui, prestiti e lavoro a cura de Il Sole 24 Ore.', 'http://www.ilsole24ore.com', 'business', 'Italian', 'it', 'Italy', '2018-08-30 16:55:09'),
(63, 'Independent', 'National morning quality (tabloid) includes free online access to news and supplements. Insight by Robert Fisk and various other columnists.', 'http://www.independent.co.uk', 'general', 'English', 'gb', 'United Kingdom', '2018-08-30 17:00:30'),
(64, 'Infobae', 'Noticias de Argentina y del mundo en tiempo real. Información, videos y fotos sobre los hechos más relevantes y sus protagonistas. Léelo antes en infobae.', 'http://www.infobae.com/?noredirect', 'general', 'Spanish', 'ar', 'Argentina', '2018-08-30 16:55:09'),
(65, 'InfoMoney', 'No InfoMoney você encontra tudo o que precisa sobre dinheiro. Ações, investimentos, bolsas de valores e muito mais. Aqui você encontra informação que vale dinheiro!', 'http://www.infomoney.com.br', 'business', 'Portuguese', 'br', 'Brazil', '2018-08-30 16:55:09'),
(66, 'La Gaceta', 'El diario de Tucumán, noticias 24 horas online - San Miguel de Tucumán - Argentina - Ultimo momento - Ultimas noticias.', 'http://www.lagaceta.com.ar', 'general', 'Spanish', 'ar', 'Argentina', '2018-08-30 16:55:09'),
(67, 'La Nacion', 'Información confiable en Internet. Noticias de Argentina y del mundo - ¡Informate ya!', 'http://www.lanacion.com.ar', 'general', 'Spanish', 'ar', 'Argentina', '2018-08-30 16:55:09'),
(68, 'La Repubblica', 'Breaking News, Latest News and Current News from FOXNews.com. Breaking news and video. Latest Current News: U.S., World, Entertainment, Health, Business, Technology, Politics, Sports.', 'http://www.repubblica.it', 'general', 'Italian', 'it', 'Italy', '2018-08-30 16:55:09'),
(69, 'Le Monde', 'Les articles du journal et toute l\'actualit&eacute; en continu : International, France, Soci&eacute;t&eacute;, Economie, Culture, Environnement, Blogs ...', 'http://www.lemonde.fr', 'general', 'French', 'fr', 'France', '2018-08-30 16:55:09'),
(70, 'Lenta', 'Новости, статьи, фотографии, видео. Семь дней в неделю, 24 часа в сутки.', 'https://lenta.ru', 'general', 'Russian', 'ru', 'Russian Federation', '2018-08-30 16:55:09'),
(71, 'L\'equipe', 'Le sport en direct sur L\'EQUIPE.fr. Les informations, résultats et classements de tous les sports. Directs commentés, images et vidéos à regarder et à partager !', 'https://www.lequipe.fr', 'sports', 'French', 'fr', 'France', '2018-08-30 16:55:09'),
(72, 'Les Echos', 'Toute l\'actualité économique, financière et boursière française et internationale sur Les Echos.fr', 'https://www.lesechos.fr', 'business', 'French', 'fr', 'France', '2018-08-30 16:55:09'),
(73, 'Libération', 'Toute l\'actualité en direct - photos et vidéos avec Libération', 'http://www.liberation.fr', 'general', 'French', 'fr', 'France', '2018-08-30 16:55:09'),
(74, 'Marca', 'La mejor información deportiva en castellano actualizada minuto a minuto en noticias, vídeos, fotos, retransmisiones y resultados en directo.', 'http://www.marca.com', 'sports', 'Spanish', 'es', 'Spain', '2018-08-30 16:55:09'),
(75, 'Mashable', 'Mashable is a global, multi-platform media and entertainment company.', 'http://mashable.com', 'entertainment', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(76, 'Medical News Today', 'Medical news and health news headlines posted throughout the day, every day.', 'http://www.medicalnewstoday.com', 'health', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(77, 'Metro', 'News, Sport, Showbiz, Celebrities from Metro - a free British newspaper.', 'http://metro.co.uk', 'general', 'English', 'gb', 'United Kingdom', '2018-08-30 17:00:30'),
(78, 'Mirror', 'All the latest news, sport and celebrity gossip at Mirror.co.uk. Get all the big headlines, pictures, analysis, opinion and video on the stories that matter to you.', 'http://www.mirror.co.uk/', 'general', 'English', 'gb', 'United Kingdom', '2018-08-30 17:00:30'),
(79, 'MSNBC', 'Breaking news and in-depth analysis of the headlines, as well as commentary and informed perspectives from The Rachel Maddow Show, Morning Joe & more.', 'http://www.msnbc.com', 'general', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(80, 'MTV News', 'The ultimate news source for music, celebrity, entertainment, movies, and current events on the web. It\'s pop culture on steroids.', 'http://www.mtv.com/news', 'entertainment', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(81, 'MTV News (UK)', 'All the latest celebrity news, gossip, exclusive interviews and pictures from the world of music and entertainment.', 'http://www.mtv.co.uk/news', 'entertainment', 'English', 'gb', 'United Kingdom', '2018-08-30 17:00:30'),
(82, 'National Geographic', 'Reporting our world daily: original nature and science news from National Geographic.', 'http://news.nationalgeographic.com', 'science', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(83, 'National Review', 'National Review: Conservative News, Opinion, Politics, Policy, & Current Events.', 'https://www.nationalreview.com/', 'general', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(84, 'NBC News', 'Breaking news, videos, and the latest top stories in world news, business, politics, health and pop culture.', 'http://www.nbcnews.com', 'general', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(85, 'News24', 'South Africa\'s premier news source, provides breaking news on national, world, Africa, sport, entertainment, technology and more.', 'http://www.news24.com', 'general', 'English', 'za', 'South Africa', '2018-08-30 16:55:09'),
(86, 'New Scientist', 'Breaking science and technology news from around the world. Exclusive stories and expert analysis on space, technology, health, physics, life and Earth.', 'https://www.newscientist.com/section/news', 'science', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(87, 'News.com.au', 'We say what people are thinking and cover the issues that get people talking balancing Australian and global moments — from politics to pop culture.', 'http://www.news.com.au', 'general', 'English', 'au', 'Australia', '2018-08-30 16:55:09'),
(88, 'Newsweek', 'Newsweek provides in-depth analysis, news and opinion about international issues, technology, business, culture and politics.', 'http://www.newsweek.com', 'general', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(89, 'New York Magazine', 'NYMAG and New York magazine cover the new, the undiscovered, the next in politics, culture, food, fashion, and behavior nationally, through a New York lens.', 'http://nymag.com', 'general', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(90, 'Next Big Future', 'Coverage of science and technology that have the potential for disruption, and analysis of plans, policies, and technology that enable radical improvement.', 'https://www.nextbigfuture.com', 'science', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(91, 'NFL News', 'The official source for NFL news, schedules, stats, scores and more.', 'http://www.nfl.com/news', 'sports', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(92, 'NHL News', 'The most up-to-date breaking hockey news from the official source including interviews, rumors, statistics and schedules.', 'https://www.nhl.com/news', 'sports', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(93, 'NRK', 'NRK er Norges største tilbud på nett: nyheter fra Norge og verden, lokalnyheter, radio- og tv-program, podcast, vær, helse-, kultur-, underholdning-, humor- og debattstoff.', 'https://www.nrk.no', 'general', 'Norwegian', 'no', 'Norway', '2018-08-30 16:55:09'),
(94, 'Politico', 'Political news about Congress, the White House, campaigns, lobbyists and issues.', 'https://www.politico.com', 'general', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(95, 'Polygon', 'Polygon is a gaming website in partnership with Vox Media. Our culture focused site covers games, their creators, the fans, trending stories and entertainment news.', 'http://www.polygon.com', 'entertainment', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(96, 'RBC', 'Главные новости политики, экономики и бизнеса, комментарии аналитиков, финансовые данные с российских и мировых биржевых систем на сайте rbc.ru.', 'http://www.rbc.ru', 'general', 'Russian', 'ru', 'Russian Federation', '2018-08-30 16:55:09'),
(97, 'Recode', 'Get the latest independent tech news, reviews and analysis from Recode with the most informed and respected journalists in technology and media.', 'http://www.recode.net', 'technology', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(98, 'Reddit /r/all', 'Reddit is an entertainment, social news networking service, and news website. Reddit\'s registered community members can submit content, such as text posts or direct links.', 'https://www.reddit.com/r/all', 'general', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(99, 'Reuters', 'Reuters.com brings you the latest news from around the world, covering breaking news in business, politics, entertainment, technology, video and pictures.', 'http://www.reuters.com', 'general', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(100, 'RT', 'Актуальная картина дня на RT: круглосуточное ежедневное обновление новостей политики, бизнеса, финансов, спорта, науки, культуры. Онлайн-репортажи с места событий. Комментарии экспертов, актуальные интервью, фото и видео репортажи.', 'https://russian.rt.com', 'general', 'Russian', 'ru', 'Russian Federation', '2018-08-30 16:55:09'),
(101, 'RTE', 'Get all of the latest breaking local and international news stories as they happen, with up to the minute updates and analysis, from Ireland\'s National Broadcaster.', 'https://www.rte.ie/news', 'general', 'English', 'ie', 'Ireland', '2018-08-30 16:55:09'),
(102, 'RTL Nieuws', 'Volg het nieuws terwijl het gebeurt. RTL Nieuws informeert haar lezers op een onafhankelijke, boeiende en toegankelijke wijze over belangrijke ontwikkelingen in eigen land en de rest van de wereld.', 'https://www.rtlnieuws.nl/', 'general', 'Dutch', 'nl', 'Netherlands', '2018-08-30 16:55:09'),
(103, 'SABQ', 'صحيفة الكترونية سعودية هدفها السبق في نقل الحدث بمهنية ومصداقية خدمة للوطن والمواطن.', 'https://sabq.org', 'general', 'Arabic', 'sa', 'Saudi Arabia', '2018-08-30 16:55:09'),
(104, 'Spiegel Online', 'Deutschlands führende Nachrichtenseite. Alles Wichtige aus Politik, Wirtschaft, Sport, Kultur, Wissenschaft, Technik und mehr.', 'http://www.spiegel.de', 'general', 'German', 'de', 'Germany', '2018-08-30 16:55:09'),
(105, 'Svenska Dagbladet', 'Sveriges ledande mediesajt - SvD.se. Svenska Dagbladets nyhetssajt låter läsarna ta plats och fördjupar nyheterna.', 'https://www.svd.se', 'general', 'Swedish', 'se', 'Sweden', '2018-08-30 16:55:09'),
(106, 'T3n', 'Das Online-Magazin bietet Artikel zu den Themen E-Business, Social Media, Startups und Webdesign.', 'http://t3n.de', 'technology', 'German', 'de', 'Germany', '2018-08-30 16:55:09'),
(107, 'TalkSport', 'Tune in to the world\'s biggest sports radio station - Live Premier League football coverage, breaking sports news, transfer rumours &amp; exclusive interviews.', 'http://talksport.com', 'sports', 'English', 'gb', 'United Kingdom', '2018-08-30 17:00:30'),
(108, 'TechCrunch', 'TechCrunch is a leading technology media property, dedicated to obsessively profiling startups, reviewing new Internet products, and breaking tech news.', 'https://techcrunch.com', 'technology', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(109, 'TechCrunch (CN)', 'TechCrunch is a leading technology media property, dedicated to obsessively profiling startups, reviewing new Internet products, and breaking tech news.', 'https://techcrunch.cn', 'technology', 'Chinese', 'cn', 'China', '2018-08-30 16:55:09'),
(110, 'TechRadar', 'The latest technology news and reviews, covering computing, home entertainment systems, gadgets and more.', 'http://www.techradar.com', 'technology', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(111, 'The American Conservative', 'Realism and reform. A new voice for a new generation of conservatives.', 'http://www.theamericanconservative.com/', 'general', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(112, 'The Economist', 'The Economist offers authoritative insight and opinion on international news, politics, business, finance, science, technology and the connections between them.', 'http://www.economist.com', 'business', 'English', 'gb', 'United Kingdom', '2018-08-30 17:00:30'),
(113, 'The Globe And Mail', 'The Globe and Mail offers the most authoritative news in Canada, featuring national and international news.', 'https://www.theglobeandmail.com', 'general', 'English', 'ca', 'Canada', '2018-08-30 16:55:09'),
(114, 'The Guardian (AU)', 'Latest news, sport, comment, analysis and reviews from Guardian Australia', 'https://www.theguardian.com/au', 'general', 'English', 'au', 'Australia', '2018-08-30 16:55:09'),
(115, 'The Guardian (UK)', 'Latest news, sport, business, comment, analysis and reviews from the Guardian, the world\'s leading liberal voice.', 'https://www.theguardian.com/uk', 'general', 'English', 'gb', 'United Kingdom', '2018-08-30 17:00:30'),
(116, 'The Hill', 'The Hill is a top US political website, read by the White House and more lawmakers than any other site -- vital for policy, politics and election campaigns.', 'http://thehill.com', 'general', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(117, 'The Hindu', 'The Hindu. latest news, analysis, comment, in-depth coverage of politics, business, sport, environment, cinema and arts from India\'s national newspaper.', 'http://www.thehindu.com', 'general', 'English', 'in', 'India', '2018-08-30 16:55:09'),
(118, 'The Huffington Post', 'The Huffington Post is a politically liberal American online news aggregator and blog that has both localized and international editions founded by Arianna Huffington, Kenneth Lerer, Andrew Breitbart, and Jonah Peretti, featuring columnists.', 'http://www.huffingtonpost.com', 'general', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(119, 'The Irish Times', 'The Irish Times online. Latest news including sport, analysis, business, weather and more from the definitive brand of quality news in Ireland.', 'https://www.irishtimes.com', 'general', 'English', 'ie', 'Ireland', '2018-08-30 16:55:09'),
(120, 'The Jerusalem Post', 'The Jerusalem Post is the leading online newspaper for English speaking Jewry since 1932, bringing news and updates from the Middle East and all over the Jewish world.', 'https://www.jpost.com/', 'general', 'English', 'il', 'Israel', '2018-08-30 16:55:09'),
(121, 'The Lad Bible', 'The LAD Bible is one of the largest community for guys aged 16-30 in the world. Send us your funniest pictures and videos!', 'http://www.theladbible.com', 'entertainment', 'English', 'gb', 'United Kingdom', '2018-08-30 17:00:30'),
(122, 'The New York Times', 'The New York Times: Find breaking news, multimedia, reviews & opinion on Washington, business, sports, movies, travel, books, jobs, education, real estate, cars & more at nytimes.com.', 'http://www.nytimes.com', 'general', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(123, 'The Next Web', 'The Next Web is one of the world’s largest online publications that delivers an international perspective on the latest news about Internet technology, business and culture.', 'http://thenextweb.com', 'technology', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(124, 'The Sport Bible', 'TheSPORTbible is one of the largest communities for sports fans across the world. Send us your sporting pictures and videos!', 'http://www.thesportbible.com', 'sports', 'English', 'gb', 'United Kingdom', '2018-08-30 17:00:30'),
(125, 'The Telegraph', 'Latest news, business, sport, comment, lifestyle and culture from the Daily Telegraph and Sunday Telegraph newspapers and video from Telegraph TV.', 'http://www.telegraph.co.uk', 'general', 'English', 'gb', 'United Kingdom', '2018-08-30 17:00:30'),
(126, 'The Times of India', 'Times of India brings the Latest News and Top Breaking headlines on Politics and Current Affairs in India and around the World, Sports, Business, Bollywood News and Entertainment, Science, Technology, Health and Fitness news, Cricket and opinions from leading columnists.', 'http://timesofindia.indiatimes.com', 'general', 'English', 'in', 'India', '2018-08-30 16:55:09'),
(127, 'The Verge', 'The Verge covers the intersection of technology, science, art, and culture.', 'http://www.theverge.com', 'technology', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(128, 'The Wall Street Journal', 'WSJ online coverage of breaking news and current headlines from the US and around the world. Top stories, photos, videos, detailed analysis and in-depth reporting.', 'http://www.wsj.com', 'business', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(129, 'The Washington Post', 'Breaking news and analysis on politics, business, world national news, entertainment more. In-depth DC, Virginia, Maryland news coverage including traffic, weather, crime, education, restaurant reviews and more.', 'https://www.washingtonpost.com', 'general', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(130, 'The Washington Times', 'The Washington Times delivers breaking news and commentary on the issues that affect the future of our nation.', 'https://www.washingtontimes.com/', 'general', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(131, 'Time', 'Breaking news and analysis from TIME.com. Politics, world news, photos, video, tech reviews, health, science and entertainment news.', 'http://time.com', 'general', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(132, 'USA Today', 'Get the latest national, international, and political news at USATODAY.com.', 'http://www.usatoday.com/news', 'general', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(133, 'Vice News', 'Vice News is Vice Media, Inc.\'s current affairs channel, producing daily documentary essays and video through its website and YouTube channel. It promotes itself on its coverage of \"under - reported stories\".', 'https://news.vice.com', 'general', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(134, 'Wired', 'Wired is a monthly American magazine, published in print and online editions, that focuses on how emerging technologies affect culture, the economy, and politics.', 'https://www.wired.com', 'technology', 'English', 'us', 'United States of America', '2018-08-30 16:55:09'),
(135, 'Wired.de', 'Wired reports on how emerging technologies affect culture, the economy and politics.', 'https://www.wired.de', 'technology', 'German', 'de', 'Germany', '2018-08-30 16:55:09'),
(136, 'Wirtschafts Woche', 'Das Online-Portal des führenden Wirtschaftsmagazins in Deutschland. Das Entscheidende zu Unternehmen, Finanzen, Erfolg und Technik.', 'http://www.wiwo.de', 'business', 'German', 'de', 'Germany', '2018-08-30 16:55:09'),
(137, 'Xinhua Net', '中国主要重点新闻网站,依托新华社遍布全球的采编网络,记者遍布世界100多个国家和地区,地方频道分布全国31个省市自治区,每天24小时同时使用6种语言滚动发稿,权威、准确、及时播发国内外重要新闻和重大突发事件,受众覆盖200多个国家和地区,发展论坛是全球知名的中文论坛。', 'http://xinhuanet.com/', 'general', 'Chinese', 'cn', 'China', '2018-08-30 16:55:09'),
(138, 'Ynet', 'ynet דף הבית: אתר החדשות המוביל בישראל מבית ידיעות אחרונות. סיקור מלא של חדשות מישראל והעולם, ספורט, כלכלה, תרבות, אוכל, מדע וטבע, כל מה שקורה וכל מה שמעניין ב ynet.', 'http://www.ynet.co.il', 'general', 'Hebrew', 'il', 'Israel', '2018-08-30 16:55:09');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
